package com.example.trubul.productlist.AndroidKsoap.com.Wsdl2Code.WebServices.Service1;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/30/2018 7:34:44 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class InventoryProductList implements KvmSerializable {

    public VectorInventoryProduct inventoryProductList;
    public String webRepsponse;

    public InventoryProductList() {
    }

    public InventoryProductList(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("inventoryProductList")) {
            SoapObject j = (SoapObject) soapObject.getProperty("inventoryProductList");
            inventoryProductList = new VectorInventoryProduct(j);
        }
        if (soapObject.hasProperty("webRepsponse")) {
            Object obj = soapObject.getProperty("webRepsponse");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                webRepsponse = j.toString();
            } else if (obj != null && obj instanceof String) {
                webRepsponse = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return inventoryProductList;
            case 1:
                return webRepsponse;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "inventoryProductList";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "webRepsponse";
                break;
        }
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
