package com.example.trubul.productlist.AndroidKsoap.com.Wsdl2Code.WebServices.Service1;
//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/30/2018 7:34:44 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

public interface IWsdl2CodeEvents {
    public void Wsdl2CodeStartedRequest();

    public void Wsdl2CodeFinished(String methodName, Object Data);

    public void Wsdl2CodeFinishedWithException(Exception ex);

    public void Wsdl2CodeEndedRequest();
}
