package com.example.trubul.productlist.AndroidKsoap.com.Wsdl2Code.WebServices.Service1;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/30/2018 7:34:44 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class Tags implements KvmSerializable {

    public int id_tag;
    public String epc;
    public String tid;
    public String type_code;
    public String status_code;
    public int id_product;
    public String webRepsponse;

    public Tags() {
    }

    public Tags(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("id_tag")) {
            Object obj = soapObject.getProperty("id_tag");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                id_tag = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                id_tag = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("epc")) {
            Object obj = soapObject.getProperty("epc");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                epc = j.toString();
            } else if (obj != null && obj instanceof String) {
                epc = (String) obj;
            }
        }
        if (soapObject.hasProperty("tid")) {
            Object obj = soapObject.getProperty("tid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                tid = j.toString();
            } else if (obj != null && obj instanceof String) {
                tid = (String) obj;
            }
        }
        if (soapObject.hasProperty("type_code")) {
            Object obj = soapObject.getProperty("type_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                type_code = j.toString();
            } else if (obj != null && obj instanceof String) {
                type_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("status_code")) {
            Object obj = soapObject.getProperty("status_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                status_code = j.toString();
            } else if (obj != null && obj instanceof String) {
                status_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("id_product")) {
            Object obj = soapObject.getProperty("id_product");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                id_product = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                id_product = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("webRepsponse")) {
            Object obj = soapObject.getProperty("webRepsponse");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                webRepsponse = j.toString();
            } else if (obj != null && obj instanceof String) {
                webRepsponse = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return id_tag;
            case 1:
                return epc;
            case 2:
                return tid;
            case 3:
                return type_code;
            case 4:
                return status_code;
            case 5:
                return id_product;
            case 6:
                return webRepsponse;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "id_tag";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "epc";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "tid";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "type_code";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "status_code";
                break;
            case 5:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "id_product";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "webRepsponse";
                break;
        }
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
